name: landina_coupon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  http: ^0.13.5
  iconly: ^1.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  quick_actions: ^1.0.1
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad/Estedad-Thin.ttf
          weight: 100
        - asset: assets/fonts/Estedad/Estedad-Light.ttf
          weight: 200
        - asset: assets/fonts/Estedad/Estedad-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Estedad/Estedad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad/Estedad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Estedad/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad/Estedad-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Estedad/Estedad-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

  assets:
    - assets/fonts/
    - assets/svg/
